on: [push]
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    name: Validate App Crawler E2E Test
    steps:
      - name: 'ğŸ¤ŸCheckout repo'
        uses: actions/checkout@v4.1.1
      - name: 'ğŸ“³â¤µï¸ Download of Test App'
        run: curl -o app.apk "https://github.com/webdriverio/native-demo-app/releases/download/v0.4.0/Android-NativeDemoApp-0.4.0.apk"
      - name: 'ğŸ“² App Crawl'
        uses: mrgklwong/app-crawler-action@v6
        with:
          app-package-name: 'com.wdiodemoapp'
          app-location: 'app.apk'
